// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbD8ST-EYxksypZsPt2A6p1Tr3_oio5aQ',
    appId: '1:628673907353:web:b564f97994e1f5d26dc608',
    messagingSenderId: '628673907353',
    projectId: 'bftms-ad377',
    authDomain: 'bftms-ad377.firebaseapp.com',
    storageBucket: 'bftms-ad377.appspot.com',
    measurementId: 'G-8WJ5S45LK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu7fBrmc_qfZFUFmYZ-ypst65sHqCuIsE',
    appId: '1:628673907353:android:62386611ab49078b6dc608',
    messagingSenderId: '628673907353',
    projectId: 'bftms-ad377',
    storageBucket: 'bftms-ad377.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD55CXGOj6ErK6idNVkVxsUwFw1vopRCe8',
    appId: '1:628673907353:ios:e03a8f463ae42c9f6dc608',
    messagingSenderId: '628673907353',
    projectId: 'bftms-ad377',
    storageBucket: 'bftms-ad377.appspot.com',
    iosBundleId: 'techbridgesolusions.net.bruhFinanceTms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD55CXGOj6ErK6idNVkVxsUwFw1vopRCe8',
    appId: '1:628673907353:ios:e03a8f463ae42c9f6dc608',
    messagingSenderId: '628673907353',
    projectId: 'bftms-ad377',
    storageBucket: 'bftms-ad377.appspot.com',
    iosBundleId: 'techbridgesolusions.net.bruhFinanceTms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbD8ST-EYxksypZsPt2A6p1Tr3_oio5aQ',
    appId: '1:628673907353:web:b2665ea9ffc9e4556dc608',
    messagingSenderId: '628673907353',
    projectId: 'bftms-ad377',
    authDomain: 'bftms-ad377.firebaseapp.com',
    storageBucket: 'bftms-ad377.appspot.com',
    measurementId: 'G-WX4M8SEFQE',
  );
}
